services:
  api:
    container_name: pool-tournament-manager-api
    image: ghcr.io/martinbarreiroo/pool-tournament-manager:latest
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      sqlserver:
        condition: service_healthy
  sqlserver:
    container_name: pool-tournament-manager-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_USER: ${SQLSERVER_USER:-sa}
      MSSQL_DATABASE: ${SQLSERVER_DATABASE:-pool-tournament-manager-db}
      MSSQL_SA_PASSWORD: ${SQLSERVER_SA_PASSWORD:-Password123!}
      MSSQL_SA_HOST: ${SQLSERVER_SA_HOST:-localhost}
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  sqlserver-data:
    driver: local
