#!/bin/bash

echo "*********************************************************"
echo "Running C# code formatter... "
echo "*********************************************************"

# Change to the root directory of the project
# shellcheck disable=SC2164
cd "$(dirname "$0")/.."

# Run dotnet format on the solution
dotnet format Pool.sln
format_status=$?

if [ "$format_status" -ne 0 ]; then
    echo "*********************************************************"
    echo "       ********************************************      "
    echo 1>&2 "C# code formatting check failed."
    echo "Run 'dotnet format PoolTournamentManager.sln' in your terminal to fix formatting issues."
    echo "       ********************************************      "
    echo "*********************************************************"
    exit 1
fi

# Check for analyzer warnings/errors
dotnet build --no-incremental --nologo /warnaserror
build_status=$?

if [ "$build_status" -ne 0 ]; then
    echo "*********************************************************"
    echo "       ********************************************      "
    echo 1>&2 "C# analyzer warnings/errors found."
    echo "Fix code style issues and warnings before committing."
    echo "       ********************************************      "
    echo "*********************************************************"
    exit 1
fi

# Add all changes to the staging area
echo "*********************************************************"
echo "All formatting checks passed. Adding changes to staging area... "
echo "*********************************************************"

git add .

# Exit
exit 0