name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/pool-tournament-manager:latest \
            -t ghcr.io/${{ github.repository_owner }}/pool-tournament-manager:${{ github.sha }} .

      - name: Push Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/pool-tournament-manager:latest
          docker push ghcr.io/${{ github.repository_owner }}/pool-tournament-manager:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Configure Azure App Service to use GHCR image
        run: |
          az webapp config container set \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RG }} \
            --docker-custom-image-name ghcr.io/${{ github.repository_owner }}/pool-tournament-manager:${{ github.sha }} \
            --docker-registry-server-url https://ghcr.io \
            --docker-registry-server-user ${{ github.actor }} \
            --docker-registry-server-password ${{ secrets.GHCR_PULL_TOKEN }}

      - name: Restart Azure App
        run: |
          az webapp restart \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RG }}